### ISSUE TITLE
Something seems... bolder

### ISSUE THREAD

**Issue by jacobwgillespie** [swashata/vscode-beautiful-ui#23]
Hi, first thank you so much for this awesome collection of themes! 🎉 

One question, and it's possible that this is something misconfigured on my end - after upgrading to v1.5.0, certain keywords seem a lot bolder than before, almost too bold, and feels kinda heavy.  

For example, here's a screenshot of the website preview next to the editor with the same contents:

<img width="1920" alt="Screenshot 2020-03-17 at 08 57 46 (2)" src="https://user-images.githubusercontent.com/130874/76839710-e4395100-682d-11ea-84e2-0d5fa41715d3.png">

Was this an intentional change?  Is something broken on my end?  I believe the upgrade to 1.5.0 is the culprit, though my VS Code updated itself as well.

**Comment by swashata** [comment]
Hi,

The website is using shiki which doesn't do bold and italics on the preview.

But you are absolutely correct about the boldness. I was thinking about this too. The bold seems too much. I don't know if this is something to do with semantic highlighting or new vscode text rendering, but it certainly isn't easy on eyes. So I will revert the bold in the next update.

**Comment by swashata** [comment]
Also do try this https://superuser.com/questions/1437445/why-vscode-fonts-always-look-bold-in-macos

**Comment by swashata** [comment]
So I have released new version 1.6.0 and removed the bold styles completely (except from markdown bold). Also I have tweaked a few color tokens to make things more consistent. Do check it out and let me know.

**Comment by jacobwgillespie** [comment]
Thank you again, that fixed it! 🎉 ❤️
