### ISSUE TITLE
Remove editorOverviewRuler styles

### ISSUE THREAD

**Issue by ColCh** [swashata/vscode-beautiful-ui#3]
VSCODE defines own colors for rules 

https://github.com/Microsoft/vscode/blob/749eb1ebcd536083627f90c7e7abd14b1ef94af3/src/vs/editor/common/view/editorColorRegistry.ts#L56-L59

and it has different colors for light theme, dark theme, high contrast theme

But why remove from current themes?

1. They are not contrast and hard to notice (as for me)

2. Other themes [like Atom Light](https://github.com/akamud/vscode-theme-onelight/blob/master/themes/OneLight.json) doesn't define this color replaces

3. Default vscode colors are pretty good and contrast

**Comment by ColCh** [comment]
hm... or just make these colors on scrollbar darker?

**Comment by swashata** [comment]
Can you show me a screenshot of what you are referring to?

**Comment by ColCh** [comment]
Sure. Please notice gutters at the right side, on scrollbar

standart theme

![image](https://user-images.githubusercontent.com/599439/41836076-502dcc82-7862-11e8-84e3-ab96d15987a9.png)

ayu this : https://github.com/teabyii/vscode-ayu

![image](https://user-images.githubusercontent.com/599439/41836214-b6944f78-7862-11e8-9f52-1e869c6cf5e5.png)

and and bui-ayu (current project)

![image](https://user-images.githubusercontent.com/599439/41836180-998a2d80-7862-11e8-861a-9c8ff358629d.png)


Gutters on scrollbar are hard to notice using bui-ayu, or it's just for me?

**Comment by swashata** [comment]
You are right. It looks like I have the same color for gutter and the scrollbar/ruler. The color for the ruler shouldn't be transparent.

I will change this to have solid color instead.

**Comment by ColCh** [comment]
Sounds good. Any preview?

**Comment by swashata** [comment]
How is this?

<img width="1614" alt="screen shot 2018-06-29 at 8 32 39 pm" src="https://user-images.githubusercontent.com/1623381/42099642-99780a98-7bdb-11e8-8bff-d30bfcd32670.png">

**Comment by swashata** [comment]
I have published 1.3.0 with the changes. Feel free to close the issue when you update.

**Comment by ColCh** [comment]
Thank you! Looks contrast now

![image](https://user-images.githubusercontent.com/599439/42117725-0e36b020-7c07-11e8-9d9a-44308c6b995c.png)
