### ISSUE TITLE
Support for Breadcrumbs

### ISSUE THREAD

**Issue by ghost** [swashata/vscode-beautiful-ui#4]
In code 1.26 breadcrumbs have been added. It would be nice if these themes had support for it.

**Comment by swashata** [comment]
Hi,

You closed this issue? Was it accidental?

**Comment by ghost** [comment]
Oops, yeah sorry.

**Comment by swashata** [comment]
No problem. Do you have anything in mind about the design?

**Comment by ghost** [comment]
Not really. Would just appreciate consistency with the current theme.

**Comment by ghost** [comment]
VSCode modified the breadcrumbs default colors in code-insiders so there's no need to customize them anymore.
