### ISSUE TITLE
Highlight python keyword parameters

### ISSUE THREAD

**Issue by zenxme** [swashata/vscode-beautiful-ui#5]
Hi, I really like your theme. But there is a small problem. Keyword parameters in python are not highlighted.

![theme1](https://user-images.githubusercontent.com/31642936/53787468-ec438d00-3f59-11e9-9072-a8d3a269cc87.jpg)

Here are some themes that highlight keyword parameters.

[material-theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
![theme2](https://user-images.githubusercontent.com/31642936/53787545-375da000-3f5a-11e9-8c44-6de8e92120c1.jpg)

[monokai-pro](https://marketplace.visualstudio.com/items?itemName=monokai.theme-monokai-pro-vscode)
![theme3](https://user-images.githubusercontent.com/31642936/53787551-39bffa00-3f5a-11e9-98ee-5279ab15953b.jpg)

**Comment by swashata** [comment]
Hello,

I don't know python :), but if you can provide some sample code and tell me which words should be highlighted with what color, I can make that happen.

**Comment by zenxme** [comment]
There's always a '=' behind python's keyword parameter. For more details, see: https://treyhunner.com/2018/04/keyword-arguments-in-python/
Many thanks for your reply and all of your contribution.
